### ISSUE TITLE
Having error while using in Android

### ISSUE THREAD

**Issue by Ayasha01** [s4kibs4mi/PultusORM#11]
Facing problem while using the project in one of my android project.

Error log:
```
E/SQLiteLog: (1) near "$change": syntax error
                                                                            java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693) 
                                                                             Caused by: java.sql.SQLException: android.database.sqlite.SQLiteException: near "$change": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS UserSession(accessToken TEXT, phoneNumber TEXT, refreshToken TEXT, sessionId INTEGER PRIMARY KEY AUTOINCREMENT, createTime BIGINT, endTime BIGINT, $change TEXT, serialVersionUID BIGINT);
                                                                                at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                                at org.sqldroid.SQLDroidConnection.chainException(SQLDroidConnection.java:158)
```

**Comment by s4kibs4mi** [comment]
@Ayasha01 issue solved in version v1.3
