### ISSUE TITLE
Null pointer accessing SQLDroid

### ISSUE THREAD

**Issue by mikepschneider** [s4kibs4mi/PultusORM#19]
I have this code to init and read/write my database:

`
    DataClass data = ...
    String appPath = getApplicationContext().getFilesDir().getAbsolutePath();
    pultusORM = new PultusORM("test.db", appPath);
     pultusORM.save(data);

     pultusORM.close();

     List<Object> data2 = pultusORM.find(new DataClass());
`

When it hits the last line I get this error:

`
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.sqldroid.SQLiteDatabase.execSQL(java.lang.String)' on a null object reference
                                                                            at org.sqldroid.SQLDroidStatement.execute(SQLDroidStatement.java:96)
                                                                            at ninja.sakib.pultusorm.core.PultusORMQuery.createTable(PultusORMQuery.kt:313)
                                                                            at ninja.sakib.pultusorm.core.PultusORMQuery.get(PultusORMQuery.kt:109)
                                                                            at ninja.sakib.pultusorm.core.PultusORM.find(PultusORM.kt:112)
                                                                            at com.dronebase.pilotapp.feature.clientmission.ClientMissionPresenter$3.run(ClientMissionPresenter.java:121)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
`

Any help?

**Comment by s4kibs4mi** [comment]
@mikepschneider it could be because of you have closed the connection on 2nd line from last and then tried to pull data.

**Comment by mikepschneider** [comment]
Ah ok I thought maybe that was closing the transaction.  Now its working ok.
