### ISSUE TITLE
Unsupported data types are not being ignored on select

### ISSUE THREAD

**Issue by CliffBrown** [s4kibs4mi/PultusORM#21]
Ignoring unsupported data types does not appear to work on selecting from the db. While inserting works without issue, selecting causes an exception to be thrown.

```
Exception in thread "Thread-2" ninja.sakib.pultusorm.exceptions.PultusORMException: Malformed query <SELECT * FROM PullRequest;>. Caused by Unsupported data type.
	at ninja.sakib.pultusorm.core.UtilsKt.throwback(Utils.kt:62)
	at ninja.sakib.pultusorm.core.PultusORMQuery.get(PultusORMQuery.kt:116)
	at ninja.sakib.pultusorm.core.PultusORM.find(PultusORM.kt:112)
```

**Comment by CliffBrown** [comment]
The issue was not because of an unsupported type as much as an Int field was cast to a String when the table was built.
