### ISSUE TITLE
beginner problem 

### ISSUE THREAD

**Issue by iainrs** [s4kibs4mi/PultusORM#24]
I'm just starting with Kotlin (using Intellij IDEA) and am trying to replicate an application that I have written in Python which uses an Sqlite datbase.

PultusORM seemed to offer the best way of processing this.
I've written a small testbed program (testdb.kt) but I'm having problems with calling PultusORM 
 val pultusORM: PultusORM = PultusORM("/home/iain/IdeaProjects/test.db") `
_gives_
Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/format/DateTimeFormat
	at ninja.sakib.pultusorm.core.UtilsKt.<clinit>(Utils.kt:29)
	at ninja.sakib.pultusorm.core.PultusORM.connect(PultusORM.kt:56)
	at ninja.sakib.pultusorm.core.PultusORM.<init>(PultusORM.kt:33)
	at TestdbKt.main(testdb.kt:31)
Caused by: java.lang.ClassNotFoundException: org.joda.time.format.DateTimeFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more`

I copied the latest .jar to the Library.

The source and output are attached (pultusorm.txt) as well as  the IDEA page(putusorm.png) 

I expect the problem is due to my ignorance but cannot see where.

![pultusorm](https://user-images.githubusercontent.com/5394974/33276327-311e2bae-d38d-11e7-9085-1cdc297c7032.png)
[pultusortm.txt](https://github.com/s4kibs4mi/PultusORM/files/1506576/pultusortm.txt)

**Comment by s4kibs4mi** [comment]
Hello @iainrs thanks for reporting the issue. In case you are using the jar you have to include dependency jars too. Preferred way is to use gradle or maven based project as then dependencies will be included automatically by gradle/maven build system.

Dependencies are,
* com.google.code.gson - version 2.7
* com.eclipsesource.minimal-json - version 0.9.4
* org.xerial.sqlite-jdbc - version 3.14.2.1
* org.sqldroid:sqldroid - version 1.0.3
* joda-time.joda-time - version 2.9.9
